### ISSUE TITLE
The iso does not work when using Ventoy

### ISSUE THREAD

**Issue by AllevatoreAnonimo** [Special-Niewbie/HandleOS#5]
The iso will not install if you use the much more practical Ventoy instead of Rufus.
The disk asks for a windows licence and if it is given it says it is incorrect (tried both a genuine professional and a genuine enterprise key).
However, if I don't change any settings and launch the installation immediately after the language prompt, the installer skips the licence prompt screen and suggests which disk to install to.
Unfortunately, however, the installer stops running shortly afterwards because it cannot read the installation files (this is most likely due to a lack of compatibility with ventoy).

Platform used: Steam Deck LCD
Installation iso used: HandleOS_23H2v2.iso

**Comment by Special-Niewbie** [comment]
> The iso will not install if you use the much more practical Ventoy instead of Rufus. The disk asks for a windows licence and if it is given it says it is incorrect (tried both a genuine professional and a genuine enterprise key). However, if I don't change any settings and launch the installation immediately after the language prompt, the installer skips the licence prompt screen and suggests which disk to install to. Unfortunately, however, the installer stops running shortly afterwards because it cannot read the installation files (this is most likely due to a lack of compatibility with ventoy).
> 
> Platform used: Steam Deck LCD Installation iso used: HandleOS_23H2v2.iso

Thank you for testing the ISO. I haven't had anyone use Ventoy until now, and I don't use it myself, so I'm sorry, but with Rufus, Balena Etcher, or other tools, no one has encountered issues. Regarding the license, I'm not sure which one you used, but HondleOS is Windows Home, so if you tried an Enterprise or Professional license, it won't be compatible. All Handle systems are produced with a Windows Home license, which activates automatically. As for Steam Deck, we've been hearing from many users that Valve hasn't released some drivers for Windows (especially for the Deck LCD version), and this causes Windows to miss important components for stable functionality. Many users are unhappy with Valve's Windows Implementations when they are discovering this because, while the drivers claim to be complete, some are missing, and you'll likely have a poor experience when switching to Windows. ;)

**Comment by AllevatoreAnonimo** [comment]
Ti ringrazio per la tempestiva risposta. Chiudo il post.
